version: '3.3'

services:
  db:
    image: mysql:9.1
    command: --innodb-log-file-size=500M --innodb_strict_mode=0
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - /d/db:/var/lib/mysql

  dev:
    depends_on:
      - db
    image: rapporteket/nordicscir-dev:nightly
    volumes:
      #- ~/.ssh:/home/rstudio/.ssh
      - ~/.gitconfig:/home/rstudio/.gitconfig
      - config:/home/rstudio/rap_config
      - /c/Users/Lena Ringstad Olsen/.ssh:/home/rstudio/speiler_.ssh
       #- ~/.gitconfig:/home/rstudio/.gitconfig
      - /d/mydata:/home/rstudio/mydata
      - /c/ResultattjenesteGIT/nordicscir:/home/rstudio/nordicscir

    ports:
      - "8787:8787"
      - "3838:3838"
    dns:
      - 8.8.8.8
    restart: "no"
    environment:
      USERID: $USERID
      PASSWORD: password
      DB_HOST: db
      DB_USER: root
      DB_PASS: root

  app_norscir:
    depends_on:
      - dev
    image: rapporteket/norscir:latest
    volumes:
      - config:/app/R
    ports:
      - "3008:3838"
    restart: "no"
    environment:
      R_RAP_CONFIG_PATH: /app/R
      R_RAP_INSTANCE: DEV

  app_nordicscir:
    depends_on:
      - dev
    image: rapporteket/nordicscir:latest
    volumes:
      - config:/app/R
    ports:
      - "3009:3838"
    restart: "no"
    environment:
      R_RAP_CONFIG_PATH: /app/R
      R_RAP_INSTANCE: DEV
  
  adminer:
    depends_on:
      - db
    image: adminer
    restart: "no"
    environment:
      ADMINER_PLUGINS: frames
    ports:
      - 8888:8080

volumes:
  config:
