x-environment: &environment
  LOGS_DB: db_log
  NORDICSCIR_DB: db_data
  AUTOREPORT_DB: db_autoreport
  MYSQL_HOST: db
  MYSQL_USERNAME: user
  MYSQL_PASSWORD: password
  FALK_APP_ID: 80
  FALK_EXTENDED_USER_RIGHTS: "[{\"A\":80,\"R\":\"LC\",\"U\":1},{\"A\":80,\"R\":\"SC\",\"U\":2},{\"A\":81,\"R\":\"LC\",\"U\":2}]"
  USERORGID: "pilot"
  SHINYPROXY_USERNAME: test@tester.no
  SHINYPROXY_USERGROUPS: "pilot"
  R_RAP_INSTANCE: "QAC"


services:

  db:
    image: mysql:8
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    entrypoint:
      sh -c "
        echo 'CREATE DATABASE IF NOT EXISTS db_log; CREATE DATABASE IF NOT EXISTS db_autoreport; CREATE DATABASE IF NOT EXISTS db_data;' > /docker-entrypoint-initdb.d/init.sql;
        /usr/local/bin/docker-entrypoint.sh  --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      "
    ports:
      - 3306:3306 

  app:
    depends_on:
      - db
    image: rapporteket/nordicscir:nhn
    ports:
      - 3838:3838
    volumes:
      - ./data-raw/config:/app/R
    environment:
      R_RAP_CONFIG_PATH: /app/R
      << : *environment

  dev:
    depends_on:
      - db
    image: rapporteket/pilot-dev:main
    volumes:
      - ~/.ssh:/home/rstudio/.ssh
      - ~/.gitconfig:/home/rstudio/.gitconfig
      - .:/home/rstudio/nordicscir
      - ../rapbase/.:/home/rstudio/rapbase
    ports:
      - "8787:8787"
    restart: "no"
    environment:
      << : *environment
      DISABLE_AUTH: "true"
      R_RAP_CONFIG_PATH: /home/rstudio/nordicscir/data-raw/config

  adminer:
    depends_on:
      - db
    image: adminer
    restart: "no"
    environment:
      ADMINER_PLUGINS: frames
    ports:
      - 8888:8080
