version: '3.3'

services:
   db:
     image: mysql:5.7
     command: --innodb-log-file-size=500M --innodb_strict_mode=0
     restart: "no"
     environment:
       MYSQL_ROOT_PASSWORD: root
     volumes:
       - D:/db:/var/lib/mysql

  dev:
    depends_on:
      - db
    image: rapporteket/nordicscir-dev:nightly
      volumes:
       - C:\Users\Lena Ringstad Olsen\.ssh:/home/rstudio/speiler_.ssh
       - ~/.gitconfig:/home/rstudio/.gitconfig
       - D:/mydata:/home/rstudio/mydata
       - C:/ResultattjenesteGIT/korona:/home/rstudio/korona
       - C:/ResultattjenesteGIT/rygg:/home/rstudio/rygg
       - C:/ResultattjenesteGIT/nordicscir:/home/rstudio/nordicscir
       - C:/ResultattjenesteGIT/intensiv:/home/rstudio/intensiv
       - C:/ResultattjenesteGIT/intensivberedskap:/home/rstudio/intensivberedskap

    ports:
      - "8787:8787"
      - "3838:3838"
    dns:
      - 8.8.8.8
    restart: "no"
    environment:
      PASSWORD: password
      DB_HOST: db
      DB_USER: root
      DB_PASS: root

  adminer:
    depends_on:
      - db
    image: adminer
    restart: "no"
    environment:
      ADMINER_PLUGINS: frames
    ports:
      - 8888:8080
