x-environment: &environment
  DB_HOST: db
  DB_USER: root
  DB_PASS: root
  FALK_APP_ID: 80
  FALK_EXTENDED_USER_RIGHTS: "[{\"A\":80,\"R\":\"LC\",\"U\":1},{\"A\":80,\"R\":\"SC\",\"U\":2},{\"A\":81,\"R\":\"LC\",\"U\":2}]"
  USERORGID: "pilot"
  SHINYPROXY_USERNAME: test@tester.no
  SHINYPROXY_USERGROUPS: "pilot"
  R_RAP_INSTANCE: "QAC"


services:
  db:
    image: mysql:8
    command: --innodb-log-file-size=500M --innodb_strict_mode=0
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: root

  app:
    depends_on:
      - db
    image: rapporteket/nordicscir:nhn
    ports:
      - 3838:3838
    environment:
      << : *environment

  dev:
    depends_on:
      - db
    image: rapporteket/pilot-dev:main
    volumes:
      - ~/.ssh:/home/rstudio/.ssh
      - ~/.gitconfig:/home/rstudio/.gitconfig
      - .:/home/rstudio/nordicscir
      - ../rapbase/.:/home/rstudio/rapbase
    ports:
      - "8787:8787"
    restart: "no"
    environment:
      << : *environment
      DISABLE_AUTH: "true"

  adminer:
    depends_on:
      - db
    image: adminer
    restart: "no"
    environment:
      ADMINER_PLUGINS: frames
    ports:
      - 8888:8080
