x-db: &db
  image: mysql:8
  restart: "no"
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: db
    MYSQL_USER: user
    MYSQL_PASSWORD: password
#  volumes:
#    - ./inst:/docker-entrypoint-initdb.d


x-environment: &environment
  MYSQL_DB: db
  MYSQL_HOST: db_data
  MYSQL_HOST_LOG: db_log
  MYSQL_HOST_AUTOREPORT: db_autoreport
  MYSQL_USERNAME: user
  MYSQL_PASSWORD: password
  FALK_APP_ID: 80
  FALK_EXTENDED_USER_RIGHTS: "[{\"A\":80,\"R\":\"LC\",\"U\":1},{\"A\":80,\"R\":\"SC\",\"U\":2},{\"A\":81,\"R\":\"LC\",\"U\":2}]"
  USERORGID: "pilot"
  SHINYPROXY_USERNAME: test@tester.no
  SHINYPROXY_USERGROUPS: "pilot"
  R_RAP_INSTANCE: "QAC"


services:
  db_data:
    <<: *db
    ports:
      - 3331:3306
  db_log:
    <<: *db
    ports:
      - 3332:3306
    volumes:
      - ./inst/db/log:/docker-entrypoint-initdb.d
  db_autoreport:
    <<: *db
    ports:
      - 3333:3306

  app:
    depends_on:
      - db_data
      - db_log
      - db_autoreport
    image: rapporteket/nordicscir:nhn
    ports:
      - 3838:3838
    volumes:
      - ./data-raw/config:/app/R
    environment:
      R_RAP_CONFIG_PATH: /app/R
      << : *environment

  dev:
    depends_on:
      - db_data
      - db_log
      - db_autoreport
    image: rapporteket/pilot-dev:main
    volumes:
      - ~/.ssh:/home/rstudio/.ssh
      - ~/.gitconfig:/home/rstudio/.gitconfig
      - .:/home/rstudio/nordicscir
      - ../rapbase/.:/home/rstudio/rapbase
    ports:
      - "8787:8787"
    restart: "no"
    environment:
      << : *environment
      DISABLE_AUTH: "true"
      R_RAP_CONFIG_PATH: /home/rstudio/nordicscir/data-raw/config

  adminer:
    depends_on:
      - db_data
      - db_log
      - db_autoreport
    image: adminer
    restart: "no"
    environment:
      ADMINER_PLUGINS: frames
    ports:
      - 8888:8080
