## Configuration of the R package 'rapbase', yaml formatted
## May contain anything, but try to keep some sensible structure and tidyness


## R
r :

  # Dummy library path
  libpath :

  # Activity logging
  raplog:
    archiveDir: logArchive
    eolDays: 730
    target: db
    key: raplog

  # Automated report data
  autoReport:
    target: db
    key: autoreport

  # Staging data
  staging:
    target: db
    key: staging
  # Scedule
  schedule :
    nocturnal :
      startHour: 0
      endHour: 8
      funs :
      - rapbase::runAutoReport
      #- norgast::norgastMakeStagingData
      - rapbase::sanitizeLog
    diurnal:
      startHour: 8
      endHour: 24
      funs:
      - rapbase::runBulletin
  # email
  smtp :
    server : localhost
    port : 2525
  sender : rapporteket@skde.no

## Github stuff
github:
  # github organization
  organization: Rapporteket
  # gist
  gistId:
    RegPulseReport: 1bcbbededd8c0b1ff26e08054f318f97
    RegDelayReport: 58126cca9efd3d373b59bc6c2a6445f1
## Registry stuff
reg:
  noric:
    nationalAccess:
      reshId: 0
      userRole: SC
      nameKey: Nasjonal
  smerte:
    nationalAccess:
      reshId: 0
      userRole: SC
      nameKey: Nasjonal
    ousAccess:
      reshId:
        - 705758
        - 705652
        - 4207789
      userRole: LC
      nameKey: 4207789
## Access tree
accesstree:
  file: accesstree/accesstree.json
  list:
    unit: AccessUnits.UnitId
    resh: AccessUnits.HealthUnitId
    role: AccessUnits.ExtraData
    parent: AccessUnits.ParentUnitId
    database: AccessUnits.HasDatabase
    external: AccessUnits.ExternalId
    title: AccessUnits.Title
    titlewithpath: AccessUnits.TitleWithPath
    validfrom: AccessUnits.ValidFrom
    validto: AccessUnits.ValidTo
